name: Reusable Deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.
      ref:
        type: string
        required: true
        description: The tag or SHA to checkout.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/login-action/tree/v3?tab=readme-ov-file#service-account-based-authentication-1
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:latest
      
      - name: Create Service declaration   
        run: |-
          export CONTAINER_IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ inputs.ref }}"
          export SERVICE_NAME="${{ vars.SERVICE_NAME }}"
          export PROJECT_ID="${{ vars.GCP_PROJECT_ID }}"
          export REVISION_TAG="${{ inputs.ref }}"
          export CLOUD_RUN_SA="${{ vars.CLOUD_RUN_SA }}"
          export ENVIRONMENT="${{ inputs.environment }}"
          envsubst < ./service-yaml/container.yaml > container-${{ inputs.environment }}.yaml
          cat container-${{ inputs.environment }}.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: ${{ vars.REGION }}
          metadata: container-${{ inputs.environment }}.yaml
